# Generated by Django 3.0.5 on 2020-05-26 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriservice', '0003_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
    ]
