# Generated by Django 3.0.5 on 2020-04-11 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduza o nome do cliente', max_length=200, verbose_name='Nome')),
                ('born', models.DateField(blank=True, help_text='Introduza a data de nascimento do cliente', null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Introduza a data da consulta', verbose_name='Data')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Introduza o peso do cliente em kg', max_digits=5, null=True, verbose_name='Peso')),
                ('client', models.ForeignKey(help_text='Selecione o cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutriservice.Client', verbose_name='Cliente')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Introduza a data do plano', null=True, verbose_name='Data')),
                ('energy', models.IntegerField(blank=True, help_text='Introduza a energia do plano em kcal', null=True, verbose_name='Energia')),
                ('client', models.ForeignKey(help_text='Selecione o cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutriservice.Client', verbose_name='Cliente')),
                ('meeting', models.ForeignKey(blank=True, help_text='Selecione a consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutriservice.Meeting', verbose_name='Consulta')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
