# Generated by Django 3.0.5 on 2020-05-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='calendar',
            field=models.CharField(max_length=200, verbose_name='Calendário Google'),
        ),
    ]
