# Generated by Django 3.0.5 on 2020-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriservice', '0003_auto_20200412_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meal1_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='meal2_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
