# Generated by Django 3.0.5 on 2020-04-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutriservice', '0004_auto_20200412_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='meal1_place',
        ),
        migrations.RemoveField(
            model_name='client',
            name='meal1_time',
        ),
        migrations.RemoveField(
            model_name='client',
            name='meal2_place',
        ),
        migrations.RemoveField(
            model_name='client',
            name='meal2_time',
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal1_time', models.TimeField(blank=True, null=True)),
                ('meal1_place', models.CharField(blank=True, max_length=200, null=True)),
                ('meal2_time', models.TimeField(blank=True, null=True)),
                ('meal2_place', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(help_text='Selecione o cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutriservice.Client', verbose_name='Cliente')),
            ],
        ),
    ]
