# Generated by Django 3.0.5 on 2020-04-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriservice', '0005_auto_20200412_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'born']},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal1_place',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal1_time',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal2_place',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meal2_time',
        ),
    ]
