# Generated by Django 3.0.5 on 2020-04-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriservice', '0007_auto_20200413_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora'),
        ),
    ]
