# Generated by Django 3.0.5 on 2020-04-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutriservice', '0008_auto_20200414_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritionist', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriservice.Client'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriservice.Client'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutriservice.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Energia'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutriservice.Meeting', verbose_name='Consulta'),
        ),
    ]
